version: "3"
services:
    mongodb:
      environment:
        - MONGO_INITDB_ROOT_USERNAME=max
        - MONGO_INITDB_ROOT_PASSWORD=secret
      volumes:
        - data:/data/db
      image: mongo
      networks:
        - goals
    backend:
      ports:
        - 80:80
      volumes:
        - logs:/logs
        - node_modules:/node_modules
      image: hristianfancha/goals-backend
      networks:
        - goals
    frontend:
      ports:
        - 3000:3000
      volumes:
        - ./frontend/src:/src
      image: hristianfancha/goals-frontend
      networks:
        - goals
networks:
    goals:
volumes:
    data:
    logs:
    node_modules: